M48
; DRILL file {KiCad 8.0.6} date 2025-03-23T16:04:09+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-23T16:04:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X158.22Y-77.51
X158.22Y-83.29
T2
X121.7Y-64.5
X121.7Y-144.75
X159.45Y-64.5
X159.45Y-144.75
M30
